@host = http://localhost:5000

###
GET {{host}}/

###
POST {{host}}/isbns
Content-Type: application/json

{ "value": "978-3-16-148410-0" }

###
POST {{host}}/isbns
Content-Type: application/json

{ "value": "not-an-isbn" }

###
POST {{host}}/emails
Content-Type: application/json

{ "value": "alice@example.com" }

###
POST {{host}}/emails
Content-Type: application/json

{ "value": "no-at-sign" }

###
POST {{host}}/money
Content-Type: application/json

{ "amount": 1.50, "currency": "EUR" }

###
POST {{host}}/money
Content-Type: application/json

{ "amount": -1.0, "currency": "EUR" }

###
POST {{host}}/loan-periods
Content-Type: application/json

{ "start": "2026-04-20", "days": 14 }
